[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SAM2CT"
version = "0.1.0"
dependencies = [
    "nibabel",
    "sam-2 @ git+https://github.com/facebookresearch/segment-anything-2.git"
]